import './style.css';

const KEY='forgeNationV7_2D';
const $=(s,r=document)=>r.querySelector(s);
const fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(n);
const money=n=>n>=1e12?'$'+(n/1e12).toFixed(1)+'T':n>=1e9?'$'+(n/1e9).toFixed(1)+'B':n>=1e6?'$'+(n/1e6).toFixed(1)+'M':'$'+Math.round(n/1e3)+'K';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

const focusDefs={industrial:{name:'Industrial',icon:'⚙',desc:'Manufacturing & industry',income:1.18,skills:{industry:2}},commercial:{name:'Commercial',icon:'▣',desc:'Trade & finance',income:1.14,skills:{commerce:2}},agricultural:{name:'Agricultural',icon:'♧',desc:'Farming & food',income:1.10,skills:{health:1,industry:1}},technological:{name:'Technological',icon:'⌘',desc:'Innovation & research',income:1.16,skills:{technology:2,education:1}},cultural:{name:'Cultural',icon:'✦',desc:'Arts & tourism',income:1.09,skills:{culture:2}}};
const skillDefs=[
 {id:'industry',name:'Industry',icon:'⚙',desc:'Production & manufacturing',base:900000,gain:0.12,color:'gold'},
 {id:'education',name:'Education',icon:'🎓',desc:'Research & skilled people',base:700000,gain:0.07,color:'blue'},
 {id:'infrastructure',name:'Infrastructure',icon:'♜',desc:'Transport & efficiency',base:1000000,gain:0.10,color:'green'},
 {id:'technology',name:'Technology',icon:'⌘',desc:'Innovation & productivity',base:1100000,gain:0.09,color:'purple'},
 {id:'health',name:'Healthcare',icon:'♥',desc:'Population wellbeing',base:650000,gain:0.055,color:'red'},
 {id:'commerce',name:'Commerce',icon:'▣',desc:'Trade & services',base:800000,gain:0.08,color:'cyan'},
 {id:'culture',name:'Culture',icon:'✦',desc:'Tourism & soft power',base:600000,gain:0.06,color:'pink'}
];
const levels=[
 {level:1,name:'Settling Nation',xp:0,unlock:'Basic economy'},
 {level:2,name:'Growing Nation',xp:1000,unlock:'Development Store'},
 {level:3,name:'Developing Nation',xp:3000,unlock:'Industrial districts'},
 {level:4,name:'Modern Nation',xp:7000,unlock:'Advanced cities'},
 {level:5,name:'Regional Power',xp:15000,unlock:'Major infrastructure'},
 {level:6,name:'Major Power',xp:30000,unlock:'Global trade'},
 {level:7,name:'Global Power',xp:60000,unlock:'World-class districts'},
 {level:8,name:'World-Class Nation',xp:120000,unlock:'National landmarks'}
];
const storeDefs=[
 {id:'factory',name:'Factory',icon:'🏭',desc:'+production income',cost:2500000,inc:120000,skill:'industry',req:2},
 {id:'university',name:'University',icon:'🎓',desc:'+research & education',cost:3200000,inc:70000,skill:'education',req:2},
 {id:'railway',name:'Railway',icon:'🚆',desc:'+logistics & trade',cost:4800000,inc:180000,skill:'infrastructure',req:3},
 {id:'airport',name:'Airport',icon:'✈',desc:'+tourism & trade',cost:6000000,inc:240000,skill:'commerce',req:4},
 {id:'hospital',name:'Hospital',icon:'🏥',desc:'+health & happiness',cost:2600000,inc:65000,skill:'health',req:2},
 {id:'stadium',name:'Stadium',icon:'🏟',desc:'+culture & reputation',cost:3500000,inc:85000,skill:'culture',req:3},
 {id:'research',name:'Technology Campus',icon:'⌘',desc:'+innovation income',cost:7200000,inc:420000,skill:'technology',req:4},
 {id:'finance',name:'Financial Center',icon:'▥',desc:'+commerce income',cost:9500000,inc:520000,skill:'commerce',req:5},
 {id:'metro',name:'Metro Network',icon:'🚇',desc:'+city efficiency',cost:12000000,inc:680000,skill:'infrastructure',req:5},
 {id:'landmark',name:'National Landmark',icon:'🏛',desc:'+reputation',cost:18000000,inc:900000,skill:'culture',req:6}
];

const defaultState={screen:'home',nation:null,lastSeen:Date.now(),toast:'',modal:null};
let state=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.nation){return {...defaultState,...x}}}catch{}return {...defaultState};}
function save(){state.lastSeen=Date.now();localStorage.setItem(KEY,JSON.stringify(state));}
function skillCost(id){const s=state.nation.skills[id]||1;const d=skillDefs.find(x=>x.id===id);return Math.round(d.base*Math.pow(1.55,s-1));}
function level(){let l=levels[0];for(const x of levels)if(state.nation.xp>=x.xp)l=x;return l;}
function nextLevel(){return levels[level().level]||null;}
function xpPct(){const l=level(),n=nextLevel();return n?clamp((state.nation.xp-l.xp)/(n.xp-l.xp)*100,0,100):100;}
function income(){const n=state.nation;let total=650000;for(const d of skillDefs)total*=1+(Math.max(0,n.skills[d.id]-1)*d.gain*0.32);for(const id in n.assets){const d=storeDefs.find(x=>x.id===id);if(d)total+=n.assets[id]*d.inc}return total*(focusDefs[n.focus]?.income||1)*(1+n.cityLevel*.055);}
function tick(){if(!state.nation)return;const now=Date.now(),elapsed=Math.max(0,Math.min(86400,(now-state.lastSeen)/1000));const earned=income()*(elapsed/86400);if(earned>1){state.nation.money+=earned;state.nation.awayEarned=(state.nation.awayEarned||0)+earned;state.nation.population+=state.nation.population*0.0000000014*elapsed;state.nation.xp+=elapsed/3600*2;state.nation.dayCount=(state.nation.dayCount||0)+elapsed/86400;}state.lastSeen=now;}
setInterval(()=>{tick();if(state.nation&&state.screen!=='create')render()},1000);

function toast(msg){state.toast=msg;render();setTimeout(()=>{if(state.toast===msg){state.toast='';render()}},2200)}
function createNation(){const name=($('#nationName')?.value||'Novara').trim()||'Novara';const focus=$('#focus')?.value||'industrial';const terrain=$('#terrain')?.value||'Coastal';const gov=$('#gov')?.value||'Republic';const pop=Number($('#pop')?.value||2.1);state.nation={name,capital:name+' City',focus,terrain,government:gov,population:pop*1e6,money:12400000,xp:0,skills:{industry:1,education:1,infrastructure:1,technology:1,health:1,commerce:1,culture:1},assets:{},cities:[{name:name+' City',type:'Capital',level:1,pop:Math.round(pop*0.42*1e6)}],cityLevel:1,reputation:12,happiness:68,dayCount:0,awayEarned:0,history:[`Founded as a ${gov.toLowerCase()} in a ${terrain.toLowerCase()} region.`]};const f=focusDefs[focus];Object.entries(f.skills).forEach(([k,v])=>state.nation.skills[k]=v);state.screen='home';state.lastSeen=Date.now();save();toast('Your nation has begun its new life.');}
function newNation(){if(confirm('Start a new nation? Your current nation will be replaced.')){state={...defaultState,screen:'create'};localStorage.removeItem(KEY);render();}}
function upgradeSkill(id){const n=state.nation,c=skillCost(id);if(n.money<c)return toast('You need more national wealth.');n.money-=c;n.skills[id]++;n.xp+=Math.round(c/25000)+80;n.history.unshift(`${skillDefs.find(x=>x.id===id).name} advanced to Level ${n.skills[id]}.`);save();toast(`${skillDefs.find(x=>x.id===id).name} upgraded`);}
function buyAsset(id){const n=state.nation,d=storeDefs.find(x=>x.id===id);if(!d)return;if(level().level<d.req)return toast(`Reach Level ${d.req} to unlock this.`);if(n.money<d.cost)return toast('Not enough wealth.');n.money-=d.cost;n.assets[id]=(n.assets[id]||0)+1;n.xp+=Math.round(d.cost/18000);if(id==='landmark')n.reputation+=8;if(id==='stadium')n.happiness+=3;if(id==='hospital')n.happiness+=4;n.history.unshift(`${d.name} opened in ${n.name}.`);save();toast(`${d.name} built`);}
function upgradeCity(){const n=state.nation,c=5000000*Math.pow(1.7,n.cityLevel-1);if(n.money<c)return toast('Save more wealth for the next city tier.');n.money-=c;n.cityLevel++;n.xp+=Math.round(c/15000);n.happiness+=2;n.cities[0].level=n.cityLevel;n.cities[0].pop*=1.12;n.history.unshift(`${n.cities[0].name} reached City Level ${n.cityLevel}.`);if(n.cityLevel%2===0)n.cities.push({name:['Harborview','New Meridian','Aurelia Heights','Rivermouth','Northgate'][Math.min(4,n.cities.length-1)],type:n.cityLevel>=6?'Metropolis':'Regional City',level:1,pop:Math.round(n.population*.08)});save();toast('Your cities grew');}
function collectAway(){tick();const e=state.nation.awayEarned||0;state.nation.awayEarned=0;save();toast(e>0?`Collected ${money(e)} while away`:'No away income yet');}

function header(){const n=state.nation,l=level();return `<header class="topbar"><div class="brand"><b>FORGE<br>A NATION</b><span>BUILD · GROW · LEAD</span></div><div class="topstats"><div><i>◉</i><span>WEALTH</span><strong>${money(n.money)}</strong><em>+${money(income())}/day</em></div><div><i>♙</i><span>POPULATION</span><strong>${fmt(n.population/1e6)}M</strong><em>+${fmt(n.population/1e6*0.0004)}M/day</em></div><div><i>★</i><span>REPUTATION</span><strong>${Math.round(n.reputation)}</strong><em>Level ${l.level}</em></div></div><button class="newnation" data-action="new">NEW NATION</button></header>`}
function nav(){const items=[['home','⌂','Home'],['cities','⌂','Cities'],['skills','◈','Skills'],['store','▦','Store'],['progress','★','Progress'],['menu','☰','Menu']];return `<nav class="bottomnav">${items.map(x=>`<button class="${state.screen===x[0]?'active':''}" data-screen="${x[0]}"><b>${x[1]}</b><span>${x[2]}</span></button>`).join('')}</nav>`}
function cityArt(city,variant='capital'){return `<div class="cityart ${variant}"><div class="sun"></div><div class="hills"></div><div class="water"></div><div class="buildings">${Array.from({length:11},(_,i)=>`<i style="height:${32+(i*17)%78}px;--x:${i}"></i>`).join('')}</div><div class="tree t1"></div><div class="tree t2"></div><strong>${esc(city)}</strong></div>`}
function progressCard(){const l=level(),nx=nextLevel();return `<div class="levelcard"><div><small>NATIONAL DEVELOPMENT</small><h2>${l.name}</h2><p>${nx?`Next: <b>${nx.name}</b> · unlocks ${nx.unlock}`:'You have reached the final development tier.'}</p></div><div class="levelnum">LV.${l.level}</div><div class="bar"><i style="width:${xpPct()}%"></i></div><small>${Math.floor(state.nation.xp).toLocaleString()} / ${nx?nx.xp.toLocaleString():'MAX'} progress</small></div>`}
function home(){const n=state.nation,l=level(),d=nextLevel();return `<main class="page homepage"><section class="hero"><div class="hero-copy"><small>YOUR NATION · LEVEL ${l.level}</small><h1>${esc(n.name)}</h1><p>${n.focus[0].toUpperCase()+n.focus.slice(1)} nation · ${n.terrain} · ${n.government}</p><div class="hero-actions"><button class="gold" data-screen="store">DEVELOP YOUR NATION</button><button class="darkbtn" data-screen="cities">VIEW CITIES</button></div></div><div class="hero-art">${cityArt(n.cities[0].name,'capital')}<div class="hero-tag"><b>City Growth</b><span>Lv. ${n.cityLevel}</span><i><em style="width:${Math.min(100,n.cityLevel*14)}%"></em></i></div></div></section>${progressCard()}<section class="fourtiles"><button data-screen="economy"><b>◉</b><strong>Economy</strong><span>Manage income & resources</span></button><button data-screen="store"><b>▣</b><strong>Development</strong><span>Build & upgrade</span></button><button data-screen="cities"><b>♙</b><strong>People</strong><span>Improve citizens' lives</span></button><button data-screen="skills"><b>◈</b><strong>Skills</strong><span>Upgrade national skills</span></button></section><section class="two"><article class="panel"><div class="panelhead"><div><small>NATIONAL WEALTH</small><h2>${money(n.money)}</h2></div><em>+${money(income())}/day</em></div><div class="income-row"><span>Income</span><b>+${money(income())}/day</b></div><div class="income-row"><span>City development</span><b>Lv.${n.cityLevel}</b></div><div class="income-row"><span>Assets</span><b>${Object.values(n.assets).reduce((a,b)=>a+b,0)}</b></div></article><article class="panel away"><small>WHILE YOU WERE AWAY</small><h3>🌙 Your nation kept growing.</h3><p>Passive income and development continue while you're away.</p><strong>${money(n.awayEarned||0)}</strong><button class="gold" data-action="collect">COLLECT</button></article></section></main>`}
function skills(){const n=state.nation;return `<main class="page"><div class="title"><div><small>NATIONAL SKILLS</small><h1>Build your capabilities.</h1><p>Every upgrade increases what your nation can earn and unlocks new development.</p></div></div><div class="skillgrid">${skillDefs.map(d=>{const lv=n.skills[d.id]||1,c=skillCost(d.id),gain=Math.round(d.gain*100*lv);return `<article class="skillcard ${d.color}"><div class="skillicon">${d.icon}</div><div class="skillcopy"><b>${d.name}</b><span>Lv. ${lv}</span><p>${d.desc}</p><strong>+${gain}% effect</strong></div><button ${n.money<c?'disabled':''} data-skill="${d.id}">UPGRADE<small>${money(c)}</small></button></article>`}).join('')}</div></main>`}
function store(){const n=state.nation;return `<main class="page"><div class="title"><div><small>DEVELOPMENT STORE</small><h1>Give your nation a better life.</h1><p>Buy permanent buildings. They generate value every day.</p></div><div class="pill">${money(n.money)} available</div></div><div class="filters"><button class="active">ALL</button><button>ECONOMIC</button><button>CIVIC</button><button>CULTURE</button><button>LUXURY</button></div><div class="storegrid">${storeDefs.map(d=>{const unlocked=level().level>=d.req,owned=n.assets[d.id]||0;return `<article class="storecard ${unlocked?'':'locked'}"><div class="storeart ${d.id}"><span>${d.icon}</span></div><div class="storebody"><div><b>${d.name}</b><p>${d.desc}</p></div><strong>${money(d.cost)}</strong><small>+${money(d.inc)}/day · ${owned} owned</small><button ${!unlocked||n.money<d.cost?'disabled':''} data-buy="${d.id}">${unlocked?'BUY':'🔒 LV.'+d.req}</button></div></article>`}).join('')}</div></main>`}
function cities(){const n=state.nation;return `<main class="page"><div class="title"><div><small>YOUR CITIES</small><h1>A nation that grows city by city.</h1><p>Develop your capital, then unlock new urban centers as your country advances.</p></div></div><section class="featured-city"><div>${cityArt(n.cities[0].name,'capital')}</div><div class="cityinfo"><small>CAPITAL CITY</small><h2>${esc(n.cities[0].name)}</h2><div class="citystats"><span>Population <b>${fmt(n.cities[0].pop/1e6)}M</b></span><span>Income <b>${money(income()*.48)}</b></span><span>Growth <b>+${n.cityLevel*2}%</b></span></div><p>Every city level changes the visual character of your country and increases national income.</p><button class="gold" data-action="cityup">UPGRADE CITY · ${money(5000000*Math.pow(1.7,n.cityLevel-1))}</button></div></section><div class="citygrid">${n.cities.slice(1).map((c,i)=>`<article class="smallcity">${cityArt(c.name,['coastal','industrial','university','residential'][i%4])}<div><small>${c.type.toUpperCase()}</small><h3>${esc(c.name)}</h3><p>${fmt(c.pop/1e6)}M citizens · Level ${c.level}</p></div></article>`).join('')||'<div class="empty">Your next city will unlock as your capital grows.</div>'}</div></main>`}
function progress(){const l=level();return `<main class="page"><div class="title"><div><small>NATION PROGRESSION</small><h1>Watch your life story unfold.</h1><p>Major levels unlock new buildings, cities and possibilities.</p></div></div><div class="progressline">${levels.map(x=>`<div class="pnode ${x.level<=l.level?'done':''} ${x.level===l.level?'current':''}"><span>${x.level}</span><b>${x.name}</b><small>${x.xp.toLocaleString()} XP</small></div>`).join('')}</div><div class="promotion"><div class="promotion-art">🏛</div><div><small>NEXT PROMOTION</small><h2>${nextLevel()?.name||'World-Class Nation'}</h2><p>${nextLevel()?nextLevel().unlock:'You have mastered the national progression.'}</p><div class="bar"><i style="width:${xpPct()}%"></i></div></div></div><section class="history"><small>NATIONAL HISTORY</small>${state.nation.history.slice(0,8).map((h,i)=>`<div><span>0${i+1}</span><p>${esc(h)}</p></div>`).join('')}</section></main>`}
function menu(){return `<main class="page"><div class="title"><div><small>MORE</small><h1>Your nation, your rules.</h1></div></div><div class="menugrid"><button data-screen="economy"><b>◉</b><span>Economy</span><small>Income & wealth</small></button><button data-screen="people"><b>♙</b><span>People</span><small>Happiness & population</small></button><button data-screen="diplomacy"><b>◎</b><span>Diplomacy</span><small>Global relationships</small></button><button data-screen="culture"><b>✦</b><span>Culture</span><small>Reputation & identity</small></button><button data-action="save"><b>↓</b><span>Save Game</span><small>Save your progress</small></button><button data-action="new"><b>↻</b><span>New Nation</span><small>Start over</small></button></div><div class="credits">Made by Sajid · <a href="https://www.instagram.com/sajidaddin" target="_blank" rel="noopener noreferrer">@sajidaddin</a> · <a href="https://www.instagram.com/sajidphobic" target="_blank" rel="noopener noreferrer">@sajidphobic</a></div></main>`}
function simple(title,sub,icon){return `<main class="page"><div class="title"><div><small>${title.toUpperCase()}</small><h1>${sub}</h1></div></div><div class="placeholder"><div>${icon}</div><h2>This part of your nation's life is coming into focus.</h2><p>The underlying simulation is already affected by your development, skills, cities and wealth.</p><button class="gold" data-screen="home">BACK HOME</button></div></main>`}
function create(){return `<main class="create"><div class="createcard"><div class="createhero"><small>FORGE A NATION</small><h1>Create your country.</h1><p>Start small. Build a life. Become a power.</p></div><label>Nation Name<input id="nationName" value="Novara" maxlength="24"></label><div class="twocol"><label>Government<select id="gov"><option>Republic</option><option>Kingdom</option><option>Federation</option><option>Commonwealth</option></select></label><label>Geography<select id="terrain"><option>Coastal</option><option>River Valley</option><option>Highlands</option><option>Plains</option></select></label></div><label>Your Focus<select id="focus">${Object.entries(focusDefs).map(([k,v])=>`<option value="${k}">${v.icon} ${v.name} — ${v.desc}</option>`).join('')}</select></label><label>Starting Population<select id="pop"><option value="1.4">1.4 million</option><option value="2.1" selected>2.1 million</option><option value="3.8">3.8 million</option><option value="5.2">5.2 million</option></select></label><button class="gold createbtn" data-action="create">CREATE NATION</button><div class="credits">Made by Sajid · <a href="https://www.instagram.com/sajidaddin" target="_blank" rel="noopener noreferrer">@sajidaddin</a> · <a href="https://www.instagram.com/sajidphobic" target="_blank" rel="noopener noreferrer">@sajidphobic</a></div></div></main>`}
function render(){tick();const root=$('#app');if(!state.nation)root.innerHTML=create();else{const body={home,skills,store,cities,progress,menu,economy:()=>simple('Economy','A living economy.', '◉'),people:()=>simple('People','A better life for citizens.', '♙'),diplomacy:()=>simple('Diplomacy','Your place in the world.', '◎'),culture:()=>simple('Culture','Build a nation people remember.', '✦')}[state.screen]||home;root.innerHTML=header()+`<div class="shell">${body()}${nav()}</div>`;if(state.toast){const t=document.createElement('div');t.className='toast show';t.textContent=state.toast;root.append(t)}}}

document.addEventListener('click',e=>{const b=e.target.closest('[data-screen],[data-action],[data-skill],[data-buy]');if(!b)return;if(b.dataset.screen){state.screen=b.dataset.screen;save();render();return}if(b.dataset.skill){upgradeSkill(b.dataset.skill);return}if(b.dataset.buy){buyAsset(b.dataset.buy);return}const a=b.dataset.action;if(a==='create')createNation();if(a==='new')newNation();if(a==='cityup')upgradeCity();if(a==='collect')collectAway();if(a==='save'){save();toast('Game saved');} });

render();
